In [1]:
import numpy as np

# NumPy - Fast Number Crunching
# NumPy is a fundamental package for numerical computing in Python

# Create arrays
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1d)
print("2D Array:\n", arr2d)

# Array properties
print("\nArray shape:", arr2d.shape)
print("Array dtype:", arr2d.dtype)
print("Array size:", arr2d.size)

# Common array creation methods
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
range_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

print("\nZeros:\n", zeros)
print("Range:", range_arr)

# Basic operations (element-wise)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:", a + b)
print("Multiplication:", a * b)
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]

Array shape: (2, 3)
Array dtype: int64
Array size: 6

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Range: [0 2 4 6 8]

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Sum: 6
Mean: 2.0
